services:
  postgres:
    image: postgres:16-alpine
    container_name: saife-pg
    environment:
      POSTGRES_USER: saife
      POSTGRES_PASSWORD: saife123
      POSTGRES_DB: saife
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U saife -d saife"]
      interval: 5s
      timeout: 5s
      retries: 5
